name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'agentic-dev-library'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  model:
    description: 'The AI model to use for the triage.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false

outputs:
  triage_summary:
    description: 'A summary of the triage.'
  labels:
    description: 'The labels suggested by the agent.'
  assignee:
    description: 'The assignee suggested by the agent.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: '22'

    - name: 'Run issue triage'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_ISSUE_NUMBER: ${{ inputs.issue_number }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_API_KEY: ${{ inputs.api_key }}
      run: |
        # Use exact pinned version of @agentic-dev-library/control to prevent supply chain attacks (CWE-829)
        npx @agentic-dev-library/control@1.2.0 triage assess "$INPUT_ISSUE_NUMBER" \
          --model "$INPUT_MODEL"
