name: 'Agentic Orchestrator'
description: 'Run a full multi-agent orchestration.'
author: 'jbcom/agentic-control'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  config_path:
    description: 'The path to the orchestration configuration file.'
    required: true
  model:
    description: 'The default Ollama model to use for the orchestration.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false

outputs:
  orchestration_summary:
    description: 'A summary of the orchestration.'

branding:
  icon: 'cpu'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: 'Run orchestrator'
      shell: bash
      run: |
        pnpm exec agentic-control orchestrate \
          --config "${{ inputs.config_path }}" \
          --model "${{ inputs.model }}" \
          --api-key "${{ inputs.api_key }}" \
          --github-token "${{ inputs.github_token }}"
