name: 'Agentic Control'
description: 'AI agent fleet management, sandboxed execution, and orchestration toolkit'
author: 'Jon Bogaty'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  command:
    description: 'Command to run (fleet, sandbox, orchestrate, status)'
    required: true
  args:
    description: 'Additional arguments for the command'
    required: false
  config:
    description: 'Path to config file'
    required: false
  github_token:
    description: 'GitHub token for API access'
    required: false
  version:
    description: '@agentic-dev-library/control version to use'
    required: false
    default: 'latest'

outputs:
  result:
    description: 'Command execution result'
    value: ${{ steps.run.outputs.result }}
  status:
    description: 'Execution status'
    value: ${{ steps.run.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: '22'

    - name: Install @agentic-dev-library/control
      shell: bash
      run: npm install -g @agentic-dev-library/control@${{ inputs.version }}

    - name: Run command
      id: run
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_CONFIG: ${{ inputs.config }}
      run: |
        # Build command array safely to prevent command injection
        declare -a CMD_ARGS
        CMD_ARGS+=("$INPUT_COMMAND")

        if [ -n "$INPUT_ARGS" ]; then
          read -r -a EXTRA_ARGS <<< "$INPUT_ARGS"
          CMD_ARGS+=("${EXTRA_ARGS[@]}")
        fi

        if [ -n "$INPUT_CONFIG" ]; then
          CMD_ARGS+=("--config" "$INPUT_CONFIG")
        fi

        echo "Running: agentic ${CMD_ARGS[*]}"

        # Run and capture output
        set +e
        OUTPUT=$(npx @agentic-dev-library/control "${CMD_ARGS[@]}" 2>&1)
        EXIT_CODE=$?
        set -e

        echo "$OUTPUT"

        # Set outputs using heredoc for multi-line safety
        {
          echo "result<<EOF"
          echo "$OUTPUT"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        if [ $EXIT_CODE -eq 0 ]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
          exit $EXIT_CODE
        fi
