name: 'Agentic PR Review'
description: 'Review a pull request using an AI agent.'
author: 'jbcom/agentic-control'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  model:
    description: 'The Ollama model to use for the review.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false

outputs:
  review_summary:
    description: 'A summary of the review.'

branding:
  icon: 'git-pull-request'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: 'Run PR review'
      shell: bash
      run: |
        pnpm exec agentic-control pr-review \
          --model "${{ inputs.model }}" \
          --api-key "${{ inputs.api_key }}" \
          --github-token "${{ inputs.github_token }}"
