name: 'Agentic CI Resolution'
description: 'Automatically fix CI failures using an AI agent.'
author: 'jbcom/agentic-control'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  model:
    description: 'The Ollama model to use for the fix.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false

outputs:
  fix_summary:
    description: 'A summary of the fix.'

branding:
  icon: 'tool'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: 'Run CI resolution'
      shell: bash
      run: |
        pnpm exec agentic-control ci-resolution \
          --model "${{ inputs.model }}" \
          --api-key "${{ inputs.api_key }}" \
          --github-token "${{ inputs.github_token }}"
